name: flutter_app_icons
description: Dynamic App Icon, provides a way to change favicon for web, and android app icon programatically.
version: 0.1.1
homepage: https://github.com/codebird/flutter_app_icons

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ">=0.3.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterAppIconsWeb
        fileName: flutter_app_icons_web.dart
      android:
        package: com.hmallah.flutter_app_icons
        pluginClass: FlutterAppIconsPlugin